background_prompts = {
    "attribute_recognition": (
        "You will be shown a random view inside a house."
        " You will come up with a simple question about object's attribute recognition"
        " based on the view, that the household owner may ask the robot."
        " You will be provided with a reference object, located at the center of the view."
        " And your question should be about the attribute recognition of the reference object."
        " If there is no salient attribute, or the image quality is too low,"
        " you can skip the view by returning corresponding messages."
        " Try to be creative in the question and make it sound like interesting scenarios"
        " when the household owner needs help."
        "\nNote:"
        " \n(1) The question is for a robot in the 3D scene, so do not refer to the"
        " image in"
        " the question."
        " \n(2) The views shown do not cover the full scene, so there might be"
        " duplicate objects in the scene. Therefore, remember to give more specific"
        " descriptions about the object in the question to avoid ambiguity."
        " \n(3) The attributes can be color, shape, material, pattern, or any other"
        " salient attributes of the object.\n"
    ),
    "functional_reasoning": (
        "You will be shown a random view inside a house."
        " You will come up with a simple question about functional reasoning"
        " based on the view, that the household owner may ask the robot."
        " You will be provided with a reference object, located at the center of the view."
        " And your question should be about the function of the reference object."
        " If there is no salient function of the reference object, or the image quality is too low,"
        " you can skip the view by returning corresponding messages."
        " Try to be creative in the question and make it sound like interesting scenarios"
        " when the household owner needs help."
        "\nNote:"
        " \n(1) The question is for a robot in the 3D scene, so do not refer to the"
        " image in"
        " the question."
        " \n(2) The question should propose a requirement and ask the robot to reason"
        " about how to fulfill the requirement."
        " \n(3) The views shown do not cover the full scene, and there are many other"
        " objects in the scene. Therefore, you need to find out unique functions of the"
        " reference object to avoid ambiguity. For example, to cool down, you need an air conditioner;"
        " to wash clothes, you need a washing machine; to store food, you need a refrigerator, etc. But to sit and rest,"
        " you can use a chair, a sofa, a bed, etc; to store books, you can use a bookshelf, a drawer, a rack, etc. So try to"
        " find out the unique function of the reference object to avoid multiple answers.\n"
    ),
    "object_recognition": (
        "You will be shown a random view inside a house."
        " You will come up with a simple question about object recognition"
        " based on the view, that the household owner may ask the robot."
        " You will be provided with a reference object, located at the center of the view."
        " And your question should be about the object recognition of the reference object."
        " If the reference object is not salient in the view, or the quality is too low,"
        " you can skip the view by returning corresponding messages."
        " Try to be creative in the question and make it sound like interesting scenarios"
        " when the household owner needs help."
        "\nNote:"
        " \n(1) The question is for a robot in the 3D scene, so do not refer to the"
        " image in"
        " the question."
        " \n(2) The views shown do not cover the full scene, so there might be"
        " duplicate objects in the scene. Therefore, remember to give more specific"
        " descriptions about the object in the question to avoid ambiguity."
        " You can describe the object's attributes, location and reletive position to"
        " surrounding objects, the room and the scene it is in, etc.\n"
    ),
    "object_state_recognition": (
        "You will be shown a random view inside a house."
        " You will come up with a simple question about object state recognition"
        " based on one view, that the household owner may ask the robot."
        " You will be provided with a reference object, located at the center of the view."
        " And your question should be about the state recognition about the reference object."
        " If there is no salient state of an object, or the image quality is too low,"
        " you can skip the view by returning corresponding messages."
        " Try to be creative in the question and make it sound like interesting scenarios"
        " when the household owner needs help."
        "\nNote:"
        " \n(1) The question is for a robot in the 3D scene, so do not refer to the"
        " image in"
        " the question."
        " \n(2) The views shown do not cover the full scene, so there might be"
        " duplicate objects in the scene. Therefore, remember to give more specific"
        " descriptions about the object you want to ask about in the question to avoid ambiguity."
        " \n(3) Since you are only provided with static views, the dynamic state of an object"
        " cannot be recognized, such as whether the fan is on or off, a machine is working or not, etc."
        " So you can focus on static states such as on/off, open/close, empty/filled, leaning/erected, folded/unfolded, or any other"
        " salient states of the object.\n"
    ),
    "object_localization": (
        "You will be shown a random view inside a house."
        " You will come up with a simple question about object localization"
        " based on the view, that the household owner may ask the robot."
        " You will be provided with a reference object, located at the center of the view."
        " And your question should be about the localization of the reference object."
        " If it is hard to describe the location of the reference object based on the view, or the image quality is too low,"
        " you can skip the view by returning corresponding messages."
        " Try to be creative in the question and make it sound like interesting scenarios"
        " when the household owner needs help."
        "\nNote:"
        " \n(1) The question is for a robot in the 3D scene, so do not refer to the"
        " image in"
        " the question."
        " \n(2) The views shown do not cover the full scene, so there might be"
        " duplicate objects in the scene. Therefore, remember to give more specific"
        " descriptions about the object you want to localize in the question, avoiding multiple answers."
        " \n(3) For writing the answer of the localization problem, you need to describe the surrounding objects,"
        " the room, the scene, etc. to help people find the object.\n"
    ),
    "world_knowledge": None,
    "spatial_understanding": (
        "You will be shown a random view inside a house."
        " You will come up with a simple question about spatial understanding"
        " based on the view, that the household owner may ask the robot."
        " You will be provided with a reference object, located at the center of the view."
        " And your question should be about the spatial understanding of the reference object."
        " If there is no salient spatial information/relationship in the image, or the image quality is too low,"
        " you can skip the view by returning corresponding messages."
        " Try to be creative in the question and make it sound like interesting scenarios"
        " when the household owner needs help."
        "\nNote:"
        " \n(1) The question is for a robot in the 3D scene, so do not refer to the"
        " image in"
        " the question."
        " \n(2) The views shown do not cover the full scene, so there might be"
        " duplicate objects in the scene. Therefore, remember to give more specific"
        " descriptions about the object you want to ask about in the question to avoid ambiguity."
        " \n(3) The spatial information can be the location and orientation of the objects, the relative position of the objects,"
        " the space in the object or the room, etc.\n"
    )
}